# Generated by Django 5.2.10 on 2026-08-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_period_start',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_status',
        ),
    ]
