# Generated by Django 5.2.6 on 2026-01-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
