# Generated by Django 5.2.6 on 2025-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
