# Generated by Django 5.2.6 on 2025-10-17 14:16

from django.db import migrations
from django.utils.timezone import now

def backfill_date_active(apps, schema_editor):
    User = apps.get_model("api", "CustomUser")
    for user in User.objects.filter(date_active__isnull=True):
        user.date_active = now()
        user.save(update_fields=["date_active"])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_date_active'),
    ]

    operations = [
        migrations.RunPython(backfill_date_active),
    ]
    