# Generated by Django 5.2.6 on 2025-10-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
