# Generated by Django 5.2.6 on 2025-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
