# Generated by Django 5.2.6 on 2025-11-21 15:12

from django.db import migrations

def backfill_account_type(apps, schema_editor):
    User = apps.get_model("api", "CustomUser")
    for user in User.objects.filter(account_type__isnull=True):
        user.account_type = "manual"
        user.save(update_fields=["account_type"])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_account_type'),
    ]

    operations = [
        migrations.RunPython(backfill_account_type),
    ]
